core/urls.py
from . import views
from django.urls import path

app_name='core'
urlpatterns=[
    path('', views.welcome, name='welcome'),
]

marketing/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from . import views


app_name='marketing'
urlpatterns=[
    path('', views.index, name='index'),
    path('product/', views.product, name='product'),

]

website/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView, LogoutView
from marketing.forms import LoginForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from django.conf.urls import  url
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('core.urls')),
    path('', include('pages.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(form_class=LoginForm)),
    path('accounts/logout/', login_required(auth_views.LogoutView.as_view())),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls')),
    path('materials/',include('materials.urls')),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

templates/partials/_logincarousel.html
{% load static %}
<div id="login-carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active one">
      <img
            class="d-block w-100 h-100"
            src="{% static 'images/Stacked-Wave.svg' %}"
            alt="First slide"
          />
    </div>
    <div class="carousel-item two">
      <img
        class="d-block w-100 h-100"
        src="{% static 'images/Simple-Shiny.svg' %}"
        alt="Second slide"
      />
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#login-carousel"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#login-carousel"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/partials/_marketing-sidenav.html
<!-- Sidebar -->
{% load static %}
<link rel="stylesheet" href="{% static 'css/marketing-sidenav.css' %}" />
<div class="bg-dark border-right" id="sidebar-wrapper">
  <div class="sidebar-heading text-warning">Marketing</div>
  <div class="list-group list-group-flush" id="list-group-sidebar">
    <a href="{% url 'marketing:index' %}" class="list-group-item list-group-item-action active"
      >Dashboard</a
    >
    <a href="#" class="list-group-item list-group-item-action"
      >Orders</a
    >
    <a href="#" class="list-group-item list-group-item-action"
      >Shipment</a
    >
    <a href="#" class="list-group-item list-group-item-action"
      >Development</a
    >
    <a href="#" class="list-group-item list-group-item-action"
      >Payment</a
    >
    <a href="#" class="list-group-item list-group-item-action"
      >Customers</a
    >
    <a href="#" class="list-group-item list-group-item-action"
      >Reports</a
    >
  </div>
</div>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-dark navbar-expand-sm bg-dark mb-0">
  <a href="{% url 'login' %}" class="navbar-brand"
    ><img
      class="img-responsive"
      id="logo"
      src="{% static 'images/menon-logo.png' %}"
      alt="menon logo"
  /></a>
  <button
    class="navbar-toggler"
    data-toggle="collapse"
    data-target="#navbarMenu"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarMenu">
    <ul class="navbar-nav ml-auto" id="topNavMenu">
      <li class="nav-item">
        <div class="dropdown">
          <a
            class="nav-link px-3 dropdown-toggle"
            href="#"
            id="marketingDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            href="#"
            >Marketing</a
          >
          <div class="dropdown-menu" aria-labelledby="marketingDropdown">
            <a class="dropdown-item" href="#">Function 1</a>
            <a class="dropdown-item" href="#">Function 2</a>
            <a class="dropdown-item" href="#">Function 3</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <div class="dropdown">
          <a
            class="nav-link px-3 dropdown-toggle"
            href="#"
            id="materialDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            href="#"
            >Materials</a
          >
          <div class="dropdown-menu" aria-labelledby="materialDropdown">
            <a class="dropdown-item" href="#">Function 1</a>
            <a class="dropdown-item" href="#">Function 2</a>
            <a class="dropdown-item" href="#">Function 3</a>
          </div>
        </div>
      </li>
      <li class="nav-item"><a class="nav-link px-3" href="#">HR</a></li>
      <li class="nav-item"><a class="nav-link px-3" href="#">Finance</a></li>
      <li class="nav-item"><a class="nav-link px-3" href="#">Customer</a></li>
      <li class="nav-item"><a class="nav-link px-3" href="#">Supplier</a></li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
  </div>
  mx-1
</nav>