core/urls.py
from . import views
from django.urls import path

app_name='core'
urlpatterns=[
    path('', views.welcome, name='welcome'),
]

materials/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from . import views


app_name='materials'
urlpatterns=[
    path('', views.index, name='index'),

    path('employees_material_requests_simple/', views.employees_material_requests_simple , name='employees_material_requests_simple'),
    path('employees_material_requests_simple/add', views.employees_material_requests_simple_add , name='employees_material_requests_simple_add'),
    path('employees_material_requests_simple/delete/<int:id>/', views.employees_material_requests_simple_delete, name='employees_material_requests_simple_delete'),
    path('employees_material_requests_simple/sent_to_all_suppliers/<int:id>/', views.employees_material_requests_simple_sent_to_all_suppliers, name='employees_material_requests_simple_sent_to_all_suppliers'),
    path('employees_material_requests_simple/select_supplier/<int:id>/<int:quotation_id>/', views.employees_material_requests_simple_select_supplier, name='employees_material_requests_simple_select_supplier'),



    path('suppliers',views.suppliers,name='suppliers'),
    path('suppliers/apply/<int:id>',views.suppliers_apply,name='suppliers_apply'),
    path('suppliers/goods_delivered/<int:id>',views.goods_delivered,name='goods_delivered')


]

website/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView, LogoutView
from marketing.forms import LoginForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from django.conf.urls import  url
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('core.urls')),
    path('', include('pages.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(form_class=LoginForm)),
    path('accounts/logout/', login_required(auth_views.LogoutView.as_view())),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls')),
    path('materials/',include('materials.urls')),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

materials/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class MaterialRequest(models.Model):
	material_name = models.CharField(max_length = 50)
	quantity = models.FloatField()
	date_required_by = models.DateTimeField()
	sent_to_all_suppliers = models.BooleanField(default=False)
	quote_selected = models.ForeignKey('materials.SupplierQuotation',related_name="%(app_label)s_%(class)s_quote_selected",null=True,on_delete=models.SET_NULL)
	created_by = models.ForeignKey(User,related_name="%(app_label)s_%(class)s_created_by",on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


QUOTE_STATUS = (
	("pending", "PENDING"),
    ("approved", "APPROVED"),
    ("goods_dispatched", 'GOODS_DISPATCHED'),
    ("goods_recieved", 'GOODS_RECIEVED'),
)

# Create your models here.
class SupplierQuotation(models.Model):
	material_request = models.ForeignKey(MaterialRequest,related_name="%(app_label)s_%(class)s_material_request",on_delete=models.CASCADE)
	quantity = models.FloatField()
	date_of_supply = models.DateTimeField()
	created_by = models.ForeignKey(User,related_name="%(app_label)s_%(class)s_created_by",on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	quote_status = models.CharField(max_length=100,choices=QUOTE_STATUS,default="pending")

	class Meta:
		unique_together = ('material_request','created_by')

materials/forms.py
from django import forms

from .models import MaterialRequest, SupplierQuotation

class DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        super().__init__(**kwargs)

class MaterialRequestForm(forms.ModelForm):
	class Meta:
		model = MaterialRequest
		exclude = ['created_at','updated_at','sent_to_all_suppliers','created_by','quote_selected']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["date_required_by"].widget = DateInput()

class SupplierQuotationForm(forms.ModelForm):
	class Meta:
		model = SupplierQuotation
		exclude = ['created_at','updated_at','created_by','material_request','quote_status']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["date_of_supply"].widget = DateInput()

materials/views.py
from django.shortcuts import render

from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, JsonResponse
import json

# DRF RELATED
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated, BasePermission, BasePermission
from rest_framework import status
from rest_framework.response import Response

from django.views.decorators.csrf import csrf_protect


from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy

from django.utils.translation import ugettext as _
import django


from django.contrib.auth.decorators import login_required, permission_required
import logging
logger = logging.getLogger()
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, redirect

import materials.serializers as materials_serializers
import materials.forms as materials_forms

from website.pretty_printing import dumps
from sorcery import dict_of

from .models import MaterialRequest, SupplierQuotation
from .forms import MaterialRequestForm, SupplierQuotationForm
from django.contrib import messages
from django.db.models import OuterRef, Subquery, Prefetch


# Create your views here.
@login_required(login_url=reverse_lazy('login'))
def index(request):
     try:
          supplier = request.user.core_supplier_user
          type_user = "supplier"
          return redirect(reverse('materials:suppliers'))
     except Exception as e:
          logger.exception("user error")

          
     try:
          employee = request.user.core_employee_user
          type_user = "employee"
          return redirect(reverse('materials:employees_material_requests_simple'))
     except Exception as e:
          logger.exception("user error")

     return redirect(reverse('login'))

# Create your views here.
@login_required(login_url=reverse_lazy('login'))
def employees_material_requests_simple(request):

     mat_reqs = MaterialRequest.objects.select_related('quote_selected').prefetch_related(Prefetch('materials_supplierquotation_material_request',queryset = SupplierQuotation.objects.all().select_related('created_by')))
     return render(request, 'materials/employees_material_requests_simple.html',dict(mat_reqs=mat_reqs,title="List of Material Requests"))



@login_required(login_url=reverse_lazy('login'))
def employees_material_requests_simple_add(request):
     if request.method == 'POST':
          form = MaterialRequestForm(request.POST)
          if form.is_valid():
               obj2 = form.save(commit=False)
               obj2.created_by = request.user
               obj2.save()
               messages.success(request, 'Record Added')
               return redirect(reverse('materials:employees_material_requests_simple'))
          else:
               messages.success(request, 'Record Not Added')
               return render(request, 'materials/employees_material_requests_simple_add.html',dict(form=form,title="Add new material request"))
     else:
          form = MaterialRequestForm()
          return render(request, 'materials/employees_material_requests_simple_add.html',dict(form=form,title="Add new material request"))


@login_required(login_url=reverse_lazy('login'))
def employees_material_requests_simple_delete(request, id):
     try:
          query = MaterialRequest.objects.get(id=id)
          query.delete()
          messages.success(request, 'Record Deleted')
          return redirect(reverse('materials:employees_material_requests_simple'))
     except Exception as e:
          messages.error(request, 'Unable to Delete')
          return redirect(reverse('materials:employees_material_requests_simple'))


@login_required(login_url=reverse_lazy('login'))
def employees_material_requests_simple_sent_to_all_suppliers(request,id):
     if request.method == 'POST':
          try:
               query = MaterialRequest.objects.get(id=id)
               query.sent_to_all_suppliers = True
               query.save()
               messages.success(request, 'Sent to all Suppliers')
               return redirect(reverse('materials:employees_material_requests_simple'))
          except Exception as e:
               messages.error(request, 'Unable to Send')
               return redirect(reverse('materials:employees_material_requests_simple'))
     else:
          return redirect(reverse('materials:employees_material_requests_simple'))


@login_required(login_url=reverse_lazy('login'))
def suppliers(request):
     mat_reqs = MaterialRequest.objects.prefetch_related('materials_supplierquotation_material_request').filter(sent_to_all_suppliers=True)
     return render(request, 'materials/suppliers_main.html',dict(mat_reqs=mat_reqs,title="List of Material Requests"))


@login_required(login_url=reverse_lazy('login'))
def suppliers_apply(request,id):
     obj = MaterialRequest.objects.get(id=id)
     if request.method == 'POST':
          form = SupplierQuotationForm(request.POST)
          if form.is_valid():
               obj2 = form.save(commit=False)
               obj2.created_by = request.user
               obj2.material_request = obj
               obj2.save()
               messages.success(request, 'Applied')
               return redirect(reverse('materials:suppliers'))
          else:
               return render(request, 'materials/suppliers_apply.html',dict(form=form,title="Apply material request",obj=obj))
     else:
          form = SupplierQuotationForm()
          return render(request, 'materials/suppliers_apply.html',dict(form=form,title="Apply material request",obj=obj))


@login_required(login_url=reverse_lazy('login'))
def employees_material_requests_simple_select_supplier(request,id,quotation_id=None):
     obj = MaterialRequest.objects.get(id=id)
     if request.method == 'POST':
          try:
               quote_selected = obj.materials_supplierquotation_material_request.get(id=quotation_id)
               quote_selected.quote_status = "approved"
               quote_selected.save()
               obj.quote_selected = quote_selected
               obj.save()
               messages.success(request, 'Supplier Selected')
               return redirect(reverse('materials:employees_material_requests_simple'))
          except Exception as e:
               messages.error(request, 'Unable to Send')
               return redirect(reverse('materials:employees_material_requests_simple'))
     else:
          quotes = obj.materials_supplierquotation_material_request.all().select_related('created_by')
          return render(request, 'materials/employees_material_requests_simple_select_supplier.html',dict(quotes=quotes,title="Select material Suppliers",obj=obj))


@login_required(login_url=reverse_lazy('login'))
def goods_delivered(request,id):
     obj = SupplierQuotation.objects.get(id=id)
     if request.method == 'POST':
          try:
               obj.quote_status = "goods_dispatched"
               obj.save()
               messages.success(request, 'Status changed to Goods Dispatched')
               return redirect(reverse('materials:suppliers'))
          except Exception as e:
               messages.error(request, 'Unable to Send')
               return redirect(reverse('materials:suppliers'))
     else:
          messages.success(request, 'NOt a post request')
          return redirect(reverse('materials:suppliers'))

materials/templates/materials/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<!-- 
* Bootstrap Simple Admin Template
* Version: 2.0
* Author: Alexis Luna
* Copyright 2020 Alexis Luna
* Website: https://github.com/alexis-luna/bootstrap-simple-admin-template
-->
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Dashboard</title>
    <link href="{% static 'materials/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'materials/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet" />
    <link href="{% static 'materials/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet" />
    <link href="{% static 'materials/vendor/fontawesome/css/brands.min.css' %}" rel="stylesheet" />
    <link href="{% static 'materials/vendor/flagiconcss/css/flag-icon.min.css' %}" rel="stylesheet" />
    <link href="{% static 'materials/css/master.css' %}" rel="stylesheet" />
    <link href="{% static 'materials/vendor/datatables/datatables.min.css' %}" rel="stylesheet" />

    <script src="{% static 'materials/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'materials/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'materials/vendor/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'materials/vendor/jquery_form/js/jquery_form.js' %}"></script>
</head>

<body>
    <div class="wrapper">
        {% if type_user == "supplier" %}
            {% include "materials/navmenu_side_suppliers.html" %}
        {% else %}
            {% include "materials/navmenu_side_employees.html" %}
        {% endif %}
        <div id="body" class="active">
    		{% include "materials/navmenu_top.html" %}
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div>
                            {% for message in messages %}
                              <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                              </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 page-header">
                            <h2 class="page-title">{{title}}</h2>
                        </div>
                    </div>
                    {% block content %}{% endblock content%}
                </div>
            </div>
    	</div>

	</div>

    <script src="{% static 'materials/js/script.js' %}"></script>
</body>

</html>

materials/templates/materials/employees_material_requests_simple.html
{% extends "materials/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="row justify-content-center align-items-center my-2">
    <div class="p-2">
        <a href="{% url "materials:employees_material_requests_simple_add" %}">
            <button class="btn btn-primary btn-xs" title="Add" type="button" id="add-item"><i class="fa fa-plus-square">
                </i>
            </button>
        </a>
    </div>
    <div class="p-2">
        Add New Request
    </div>
</div>

<div class="row">
    <div class="col-12">
       <div class="table-responsive">
            <table class="mx-auto w-auto table table-striped table-bordered table-hover dataTables-devices" id="table-items">
                <thead>
                    <tr>
                        <th></th>
                        <th>Status</th>
                        <th>Material</th>
                        <th>Quantity</th>
                        <th>Required Date</th>
                        <th>Created By</th>
                        <th>Number of Suppliers Applied</th>
                        <th>Select Supplier</th>
                        <th>Suplier Quoted Quantity</th>
                        <th>Suplier Quoted Delivery Date</th>
                        <th>Suplier Status</th>
                    </tr>
                </thead>
                <tbody>
                {% for query in mat_reqs %}
                    <tr>
                        <th>
                            <form id="myForm" action={% url "materials:employees_material_requests_simple_delete" id=query.id %}  enctype="multipart/form-data" method="POST">
                                {% csrf_token %}
                                <button id="removeButton" class="btn btn-primary btn-sm table-remove-items" title="Delete"><i class="fa fa-trash"></i></button>
                            </form>
                        </th>
                        <td>
                            {% if query.sent_to_all_suppliers %}
                                <div class="p-1 bg-success text-white text-center">Sent</div>
                            {% else %}
                                <form action={% url "materials:employees_material_requests_simple_sent_to_all_suppliers" id=query.id %}  enctype="multipart/form-data" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">Send to all suppliers</button>
                                </form>
                            {% endif %}
    
                        </td>
                        <td>{{query.material_name}}</td>
                        <td>{{query.quantity}}</td>
                        <td>{{query.date_required_by}}</td>
                        <td>{{query.created_by}}</td>
                        <td>{{query.materials_supplierquotation_material_request.count}}</td>
                        
                        {% if query.quote_selected %}
                            <td><div class="p-1 bg-success text-white text-center">[{{ query.quote_selected.created_by.id }}] --> {{ query.quote_selected.created_by.username }}</div></td>
                            <td>{{query.quote_selected.quantity}}</td>
                            <td>{{query.quote_selected.date_of_supply}}</td>
                            {% if query.quote_selected.quote_status == "approved" %}
                                <td><div class="p-1 bg-warning text-white text-center">{{query.quote_selected.quote_status}}</div></td>
                            {% elif query.quote_selected.quote_status == "pending" %}
                                <td><div class="p-1 bg-secondary text-white text-center">{{query.quote_selected.quote_status}}</div></td>
                            {% elif query.quote_selected.quote_status == "goods_dispatched" %}
                                <td><div class="p-1 bg-success text-white text-center">{{query.quote_selected.quote_status}}</div></td>
                            {% else %}
                                <td>Error</td>
                            {% endif %}

                        {% else %}
                            <td>
                                {% if query.sent_to_all_suppliers %}
                                   <a href={% url 'materials:employees_material_requests_simple_select_supplier' id=query.id quotation_id=0 %}><button class="btn btn-primary">Select supplier</button></a>
                                {% else %}
                                    Not sent
                                {% endif %}
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    let removeButton = document.getElementById('removeButton');
    removeButton.onclick = function() {
        let accepted = confirm("Are you sure you want to delete this?");
        if (accepted) {
            document.getElementById('myForm').submit();
        }
    }
</script>
{% endblock content %}

materials/templates/materials/employees_material_requests_simple_add.html
{% extends "materials/base.html" %}
{% load static %}
{% load i18n %}
{# Load the tag library #}
{% load bootstrap4 %}

{% block content %}

<div class="row justify-content-center align-items-center my-2">
    <form class="form" action={% url "materials:employees_material_requests_simple_add" %} method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">
        Submit
      </button>
    </form>
</div>
{% endblock content %}

materials/templates/materials/employees_material_requests_simple_select_supplier.html
{% extends "materials/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="row justify-content-center align-items-center my-2">
       <div class="table-responsive">
            <table class="mx-auto w-auto table table-striped table-bordered table-hover dataTables-devices">
                <tbody>
                    <tr>
                        <th>
                            Request Id
                        </th>
                        <td>{{obj.id}}</td>
                    </tr>
                    <tr>
                        <th>
                            Material Name
                        </th>
                        <td>{{obj.material_name}}</td>
                    </tr>
                    <tr>
                        <th>
                            Required Quantity
                        </th>
                        <td>{{obj.quantity}}</td>
                    </tr>
                    <tr>
                        <th>
                            Required By
                        </th>
                        <td>{{obj.date_required_by}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
</div>

<div class="row">
    <div class="col-12">
       <div class="table-responsive">
            <table class="mx-auto w-auto table table-striped table-bordered table-hover dataTables-devices" id="table-items">
                <thead>
                    <tr>
                        <th></th>
                        <th>Supplier UserName and Id</th>
                        <th>Quoted Quantity</th>
                        <th>Quoted Date of Supply</th>
                    </tr>
                </thead>
                <tbody>
                {% for quote in quotes %}
                    <tr>
                        <th>
                            <form action={% url "materials:employees_material_requests_simple_select_supplier" id=obj.id quotation_id=quote.id%}  enctype="multipart/form-data" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-primary">Select Supplier</button>
                            </form>
                        </th>
                        <td>[{{quote.created_by.id}}] --> {{quote.created_by.username}}</td>
                        <td>{{quote.quantity}}</td>
                        <td>{{quote.date_of_supply}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    let removeButton = document.getElementById('removeButton');
    removeButton.onclick = function() {
        let accepted = confirm("Are you sure you want to delete this?");
        if (accepted) {
            document.getElementById('myForm').submit();
        }
    }
</script>
{% endblock content %}

materials/templates/materials/navmenu_side_employees.html
{% load static %}
{% load i18n %}

<nav id="sidebar" class="">
    <div class="sidebar-header">
        <img src="{% static 'materials/img/bootstraper-logo.png' %}" alt="bootraper logo" class="app-logo" />
    </div>
    <ul class="list-unstyled components text-secondary">
	    <li>
	        <a href="{% url "materials:employees_material_requests_simple" }">Materials Requests Simple</a>
	    </li>
	</ul>
</nav>

materials/templates/materials/navmenu_side_suppliers.html
{% load static %}
{% load i18n %}

<nav id="sidebar" class="">
    <div class="sidebar-header">
        <img src="{% static 'materials/img/bootstraper-logo.png' %}" alt="bootraper logo" class="app-logo" />
    </div>
    <ul class="list-unstyled components text-secondary">
	    <li>
	        <a href={% url 'materails:employees_material_requests_simple' %}>Material requests</a>
	    </li>
	</ul>
</nav>

materials/templates/materials/suppliers_apply.html
{% extends "materials/base.html" %}
{% load static %}
{% load i18n %}
{# Load the tag library #}
{% load bootstrap4 %}

{% block content %}

<div class="row justify-content-center align-items-center my-2">
       <div class="table-responsive">
            <table class="mx-auto w-auto table table-striped table-bordered table-hover dataTables-devices">
                <tbody>
                	<tr>
                        <th>
                        	Request Id
                        </th>
                        <td>{{obj.id}}</td>
                    </tr>
                    <tr>
                        <th>
                        	Material Name
                        </th>
                        <td>{{obj.material_name}}</td>
                    </tr>
                    <tr>
                        <th>
                        	Required Quantity
                        </th>
                        <td>{{obj.quantity}}</td>
                    </tr>
                    <tr>
                        <th>
                        	Required By
                        </th>
                        <td>{{obj.date_required_by}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
</div>

<div class="row justify-content-center align-items-center my-2">
    <form class="form" action={% url "materials:suppliers_apply" id=obj.id %} method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">
        Submit
      </button>
    </form>
</div>
{% endblock content %}

materials/templates/materials/suppliers_main.html
{% extends "materials/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-12">
       <div class="table-responsive">
            <table class="mx-auto w-auto table table-striped table-bordered table-hover dataTables-devices" id="table-items">
                <thead>
                    <tr>
                        <th></th>
                        <th>Id</th>
                        <th>Material</th>
                        <th>Required Quantity</th>
                        <th>Required Date</th>
                        <th>Quoted Quantity</th>
                        <th>Quoted Date</th>
                        <th>Quote Status</th>
                        <th>Check Goods Delivered</th>
                    </tr>
                </thead>
                <tbody>
                {% for query in mat_reqs %}
                    <tr>
                        {% if query.materials_supplierquotation_material_request.count > 0 %}
                            <td>
                                <div class="p-1 bg-success text-white text-center">Applied</div>
                            </td>
                        {% else %}
                            <td>
                                <a href={% url "materials:suppliers_apply" id=query.id %} ><button class="btn btn-primary">Apply</button></a>
                            </td>
                        {% endif %}
                        <td>{{query.id}}</td>
                        <td>{{query.material_name}}</td>
                        <td>{{query.quantity}}</td>
                        <td>{{query.date_required_by}}</td>
                        {% if query.materials_supplierquotation_material_request.count > 0 %}
                            <td>{{query.materials_supplierquotation_material_request.all.0.quantity}}</td>
                            <td>{{query.materials_supplierquotation_material_request.all.0.date_of_supply}}</td>
                            {% if query.materials_supplierquotation_material_request.all.0.quote_status == "approved" %}
                                <td><div class="p-1 bg-warning text-white text-center">{{query.materials_supplierquotation_material_request.all.0.quote_status}}</div></td>
                                <td>
                                    <form action={% url "materials:goods_delivered" id=query.materials_supplierquotation_material_request.all.0.id %} enctype="multipart/form-data" method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-primary">Confirm</button>
                                    </form>
                                </td>
                            {% elif query.materials_supplierquotation_material_request.all.0.quote_status == "pending" %}
                                <td><div class="p-1 bg-secondary text-white text-center">{{query.materials_supplierquotation_material_request.all.0.quote_status}}</div></td>
                                <td></td>
                            {% elif query.materials_supplierquotation_material_request.all.0.quote_status == "goods_dispatched" %}
                                <td><div class="p-1 bg-success text-white text-center">{{query.materials_supplierquotation_material_request.all.0.quote_status}}</div></td>
                                <td></td>
                            {% else %}
                                <td>Error</td>
                                <td></td>
                            {% endif %}
                        {% else %}
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        {% endif %}

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    let removeButton = document.getElementById('removeButton');
    removeButton.onclick = function() {
        let accepted = confirm("Are you sure you want to delete this?");
        if (accepted) {
            document.getElementById('myForm').submit();
        }
    }
</script>
{% endblock content %}